name = "pluct-business-engine"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
TTT_BASE = "https://your-ttt-host"   # where TTTranscribe runs

[kv_namespaces]
  [{ binding = "KV_USERS", id = "xxxxx" }]

# Add secrets at deploy time (do not hardcode)
# wrangler secret put ENGINE_JWT_SECRET
# wrangler secret put ENGINE_ADMIN_KEY
# wrangler secret put TTT_SHARED_SECRET
