name = "pluct-business-engine"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
TTT_BASE = "https://iamromeoly-tttranscribe.hf.space"   # where TTTranscribe runs
LOG_LEVEL = "info"                   # debug, info, warn, error
MAX_RETRIES = "3"                    # Maximum retry attempts
REQUEST_TIMEOUT = "30000"            # Default timeout in milliseconds (10 min for /transcribe endpoint)

[[kv_namespaces]]
binding = "KV_USERS"
id = "1897ec2df7a84145b59ed35d2a641d51"

[[d1_databases]]
binding = "DB"
database_name = "pluct-business-engine"
database_id = "ef0adf09-4fd4-4125-9f85-c65d6a58359b"

# Add secrets at deploy time (do not hardcode)
# wrangler secret put ENGINE_JWT_SECRET
# wrangler secret put ENGINE_ADMIN_KEY
# wrangler secret put TTT_SHARED_SECRET

