name: Deploy Pluct Business Engine

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Verify Wrangler Installation
        run: npx wrangler --version

      - name: Apply D1 Migrations (Remote)
        run: npx wrangler d1 execute pluct-db --file=./schema.sql --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
          wranglerVersion: '3'
          secrets: |
            JWT_SECRET
            WEBHOOK_SECRET
            ADMIN_SECRET
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Your worker is now live at: https://pluct-business-engine.romeo-lya2.workers.dev"
          echo "Testing health endpoint..."
          curl -f https://pluct-business-engine.romeo-lya2.workers.dev/health || echo "Health check failed - this is normal for new deployments"